/* Generated by tools/generate-service-worker.js. Do not edit by hand. */
const APP_CACHE_NAME = 'cognitive-app-1787142116466';
const MEDIA_CACHE_NAME = 'cognitive-media-v1';
const APP_ASSET_PATHS = [
  {
    "path": ".nojekyll",
    "hash": "43392b4e290e3730674e985cc7b93d291a34a5ae"
  },
  {
    "path": "README.md",
    "hash": "c196847907d05fa362da28102a39aedc4cbfafb1"
  },
  {
    "path": "css/color.css",
    "hash": "bbdb0f2cd45f62e715de317e6519321132c7f007"
  },
  {
    "path": "css/controls.css",
    "hash": "08128db1f372aa22e37998e80e3664a49dfc6949"
  },
  {
    "path": "css/shared.css",
    "hash": "0ffed186b7ed8fce1ac6eca59f83e2e748b64853"
  },
  {
    "path": "css/unified.css",
    "hash": "50a4b63c1af38fd44a6e9e3a70eab0cd4ce4de61"
  },
  {
    "path": "css/variables.css",
    "hash": "d3cd24daf824fc8967e74da06a5a49a9fc84c08b"
  },
  {
    "path": "icon-maskable.svg",
    "hash": "5420dc2904fedf870c202f0096ae7410756af788"
  },
  {
    "path": "icon.svg",
    "hash": "e921aa3d988849ef8769721c3648942ea05f7dfa"
  },
  {
    "path": "index.html",
    "hash": "26600fadb2aab84e2930b632007d4fd362542d0b"
  },
  {
    "path": "js/audio.js",
    "hash": "83ffdf67962e1437b6875ed65db2456b1b307f7a"
  },
  {
    "path": "js/boot.js",
    "hash": "e61ee874090d363258d0c3d3a69fd867dc2b173b"
  },
  {
    "path": "js/color.js",
    "hash": "94e390ced53a17cb6f5e2feb29a82c10d61a2116"
  },
  {
    "path": "js/layout.js",
    "hash": "7097af58918e6464b30c1d3355d03a6b293d201f"
  },
  {
    "path": "js/main.js",
    "hash": "161c9807c9df834079bbcd6e989dec138b5c2fd1"
  },
  {
    "path": "js/settings-layout.js",
    "hash": "327a66fa146ac66546ece588dd53a65b72ac2964"
  },
  {
    "path": "js/settings.js",
    "hash": "7f81adc35c859759488945b44a4d2b7a7e13be35"
  },
  {
    "path": "js/sw-register.js",
    "hash": "f69d3f34ad36cd86e77af866a3c8388c7dc2c0a1"
  },
  {
    "path": "js/ui.js",
    "hash": "ff8d4fc2fc66b068dea6b1d824ff929613fa49f9"
  },
  {
    "path": "js/update-flow.js",
    "hash": "aa61cde56c474841021ad3bf0241590c8e533a42"
  },
  {
    "path": "js/utils.js",
    "hash": "9446216995ab028190971e74aa497a550a96a1fc"
  },
  {
    "path": "js/worker-runtime.js",
    "hash": "41226c92c123696b6283d16b4b30167fc53c5ac5"
  },
  {
    "path": "manifest.webmanifest",
    "hash": "712b911d074f46a82bb19cd91bfee0841deadbb2"
  }
];
const MEDIA_ASSET_PATHS = [
  {
    "path": "assets/icons/back.png",
    "hash": "fa0524635c96dfd22d9d4229c365d88d5e6e2a8a"
  },
  {
    "path": "assets/icons/menu.png",
    "hash": "b8dbac1837b8c716d195b9046f54cbd2b28353b1"
  },
  {
    "path": "background.mp3",
    "hash": "efe01a681d664ec252261a1040c6f33ca037c3d0"
  },
  {
    "path": "icons/apple-touch-icon.png",
    "hash": "9d9f4f3a2cdc8afbc745d7f0642857613aaacd05"
  },
  {
    "path": "icons/icon-1024.png",
    "hash": "b2fdeb8bd8e1563420c63a51831cfaf76b36b333"
  },
  {
    "path": "icons/icon-192.png",
    "hash": "0abadd330e62812c9c87156b441a35227bf75aaa"
  },
  {
    "path": "icons/icon-512.png",
    "hash": "65f6911c705e091053c3ec42a53722ce82b5df6e"
  },
  {
    "path": "icons/icon-maskable-1024.png",
    "hash": "974b4875fdac4c1f2233a720f06ac73992fc1a25"
  },
  {
    "path": "icons/icon-maskable-512.png",
    "hash": "d982a959ac5bed01644dfb8c780eae62df8803f7"
  }
];

importScripts('js/worker-runtime.js');

createCognitiveWorker({
  self,
  appCacheName: APP_CACHE_NAME,
  mediaCacheName: MEDIA_CACHE_NAME,
  assetPaths: APP_ASSET_PATHS,
  mediaAssetPaths: MEDIA_ASSET_PATHS
});
